version: 2.1

jobs:
  fetch_and_generate:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      # Install System Dependencies
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get clean
            sudo apt-get update
            sudo apt-get install -y imagemagick ghostscript curl jq

      # Install Ollama CLI
      - run:
          name: Install Ollama CLI
          command: |
            curl -fsSL https://ollama.com/install.sh | sh && ollama --version || (echo "Ollama installation failed" && exit 1)

      # Start Ollama Service
      - run:
          name: Start Ollama Service
          command: |
            ollama serve &> ollama.log &
            sleep 10
            tail -n 10 ollama.log

      # Verify Ollama API
      - run:
          name: Verify Ollama API
          command: |
            curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
