version: 2.1

jobs:
  run-script:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      
      # Step 1: Set up Python environment
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install requests
      
      # Step 2: Run the Python script
      - run:
          name: Run Python Script
          command: |
            python script.py "sunny day" "edwardlance.lorilla.edwardlorilla1@blogger.com"
      - run:
          name: Notify Success
          command: echo "Script executed successfully!"

workflows:
  test:
    jobs:
      - run-script
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *" # Run every hour
          filters:
            branches:
              only:
                - main
    jobs:
      - run-script
